object Versions {

    const val gradlePlugin = "7.0.3"
    const val kotlin = "1.6.0"
    const val kotlinXTest = "1.5.2"
    const val androidXCore = "1.7.0"
    const val appCompat = "1.3.1"
    const val material = "1.4.0"
    const val constraintLayout = "2.1.1"
    const val lifecycleViewModel = "2.4.0"
    const val coroutines = "1.5.2"
    const val koin = "3.1.3"
    const val coil = "1.4.0"
    const val retrofit = "2.9.0"
    const val mockk = "1.12.0"
    const val junit = "4.13.2"
    const val androidXTest = "1.4.0"
    const val androidXTestJunit = "1.1.3"
    const val espresso = "3.4.0"
    const val androidXCoreTesting = "2.1.0"
    const val robolectric = "4.7"
}